name: PullRequest

on: [pull_request]

jobs:
  buildClient:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Build Client
        run:  ./gradlew prepareRunClient
  buildServer:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Build Server
        run:  ./gradlew prepareRunServer
  buildData:
    name: Build Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Build Data
        run:  ./gradlew prepareRunData